blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: 'ì´ìŠˆ ìƒì„±'
    description: 'Repoì— ì´ìŠˆë¥¼ ìƒì„±í•˜ë©°, ìƒì„±ëœ ì´ìŠˆëŠ” Jiraì™€ ì—°ë™ë©ë‹ˆë‹¤.'
    labels: []
    file: ISSUE_TEMPLATE/issue-form.yml
    type: 'yaml'
  - name: 'ğŸ› fix-template'
    description: 'ë²„ê·¸ ë°œìƒ ì‹œ ì‚¬ìš©í•´ì£¼ì„¸ìš”'
    labels: []
    file: ISSUE_TEMPLATE/fix-form.yml
    type: 'yaml'
